import random

def generate_sokoban_xsb(grid_size=7, num_boxes=2):
    # Characters
    WALL = '#'
    FLOOR = '-'
    GOAL = '.'
    BOX = '$'
    PLAYER = '@'
    BOX_ON_GOAL = '*'
    PLAYER_ON_GOAL = '+'

    # Create empty level with walls around
    level = [[FLOOR for _ in range(grid_size)] for _ in range(grid_size)]

    # Put walls around the level
    for i in range(grid_size):
        level[0][i] = WALL
        level[grid_size-1][i] = WALL
        level[i][0] = WALL
        level[i][grid_size-1] = WALL

    # Randomly place goals
    goal_positions = set()
    while len(goal_positions) < num_boxes:
        y, x = random.randint(1, grid_size-2), random.randint(1, grid_size-2)
        if level[y][x] == FLOOR:
            level[y][x] = GOAL
            goal_positions.add((y, x))

    # Randomly place boxes (on floor or goal)
    box_positions = set()
    while len(box_positions) < num_boxes:
        y, x = random.randint(1, grid_size-2), random.randint(1, grid_size-2)
        if (y, x) not in box_positions and level[y][x] in [FLOOR, GOAL]:
            if level[y][x] == GOAL:
                level[y][x] = BOX_ON_GOAL
            else:
                level[y][x] = BOX
            box_positions.add((y, x))

    # Randomly place player (not on box)
    while True:
        y, x = random.randint(1, grid_size-2), random.randint(1, grid_size-2)
        if (y, x) not in box_positions:
            if level[y][x] == GOAL:
                level[y][x] = PLAYER_ON_GOAL
            elif level[y][x] == FLOOR:
                level[y][x] = PLAYER
            break

    # Convert level to string
    level_str = "\n".join("".join(row) for row in level)
    level_str += "\nRandom Sokoban Level\nGenerated by Python"

    return level_str

# Example usage
if __name__ == "__main__":
    print(generate_sokoban_xsb())
